name: Deploy to heroku.

on:
  push:
    branches: [dev]

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name : setu up heroku
        run: |
          curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
          
      - name: Package Service with Maven
        run:
          mvn clean package -DskipTests -Pnative  -Dquarkus.native.container-build=true
          docker build -f src/main/docker/Dockerfile.native -t quarkus/kairos_dev .
          heroku login
