name: Deploy to heroku.

on:
  push:
    branches: [dev]

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: print files 1
        run: ls
      - name: Package Service with Maven
        run: mvn clean package -DskipTests -Pnative  -Dquarkus.native.container-build=true
      - name: print files 2
        run: |
          ls
          sudo apt-get install tree
          tree target
          tree src
      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          # email: ${{ secrets.HEROKU_EMAIL }}
          # heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          # heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          email: odongoedwin69@gmail.com
          heroku_api_key: 796e4fd8-6afa-46a9-910d-8e4868f624e7
          heroku_app_name: sacco-backends
          dockerfile_directory: ./src/main/docker
          dockerfile_name: Dockerfile.native
          docker_options: "--no-cache"
          process_type: web